name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # --- Checkout code ---
    - name: Checkout Code
      uses: actions/checkout@v3

    # --- Build Docker Image ---
    - name: Build Docker Image
      run: |
        docker build -t kharwararun/myapp:latest .

    # --- Log in to Docker Hub ---
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # --- Push Docker Image ---
    - name: Push Docker Image
      run: |
        docker push kharwararun/myapp:latest

    # --- Deploy to EC2 ---
    - name: Deploy on EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install Docker if missing
          if ! command -v docker &> /dev/null
          then
            sudo apt update -y
            sudo apt install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
          fi

          # Stop and remove old container
          docker stop myapp || true
          docker rm myapp || true
          docker rmi kharwararun/myapp:latest || true

          # Pull and run latest Docker image
          docker pull kharwararun/myapp:latest
          docker run -d -p 5000:5000 --name myapp --restart always kharwararun/myapp:latest
