name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # --- Checkout Code ---
    - name: Checkout Code
      uses: actions/checkout@v3

    # --- Build Docker Image ---
    - name: Build Docker Image
      run: |
        docker build -t kharwararun/myapp:latest .

    # --- Log in to Docker Hub ---
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # --- Push Docker Image ---
    - name: Push Docker Image
      run: |
        docker push kharwararun/myapp:latest

    # --- Deploy to EC2 (with Docker installation) ---
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}     # <-- EC2 public IP/DNS
        username: ubuntu                  # <-- default user for Ubuntu AMIs
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install Docker if not present
          if ! command -v docker &> /dev/null
          then
            echo "Docker not found. Installing..."
            sudo apt update -y
            sudo apt install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
            sudo usermod -aG docker $USER
          fi

          # Pull & restart container
          docker pull kharwararun/myapp:latest
          docker stop myapp || true
          docker rm myapp || true
          docker run -d --name myapp -p 5000:5000 kharwararun/myapp:latest
