name: Deploy to EC2

on:
  push:
    branches:
      - main  # pipeline triggers only on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "."
        target: "~/app"

    - name: Install Docker & Deploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install Docker if missing
          if ! command -v docker &> /dev/null
          then
            echo "Docker not found. Installing..."
            sudo apt update -y
            sudo apt install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
          fi

          # Add user to Docker group
          sudo usermod -aG docker ubuntu
          newgrp docker

          # Deploy application
          cd ~/app
          docker stop myapp || true
          docker rm myapp || true
          docker build -t myapp:latest .
          docker run -d -p 5000:5000 --name myapp myapp:latest
