name: Deploy to EC2 / ASG

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # --- Checkout code ---
    - name: Checkout Code
      uses: actions/checkout@v3

    # --- Log in to Docker Hub ---
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # --- Build Docker image with commit SHA and push ---
    - name: Build & Push Docker Image
      run: |
        docker build -t kharwararun/app:${GITHUB_SHA} .
        docker push kharwararun/app:${GITHUB_SHA}

    # --- Update commit ID in AWS Secrets Manager ---
    - name: Update commit ID in Secrets Manager
      run: |
        aws secretsmanager put-secret-value \
          --secret-id secrets \
          --secret-string "{\"commit_id\":\"${GITHUB_SHA}\"}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-south-1

    # --- Deploy to EC2 via SSH ---
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install Docker if missing
          if ! command -v docker &> /dev/null; then
            echo "Installing Docker..."
            sudo apt update -y || true
            sudo apt install -y docker.io jq awscli || true
            sudo systemctl enable docker || true
            sudo systemctl start docker || true
          fi

          # Fetch commit ID from Secrets Manager
          SECRET_JSON=$(aws secretsmanager get-secret-value \
            --secret-id secrets --query SecretString --output text)
          COMMIT_ID=$(echo $SECRET_JSON | jq -r '.commit_id')

          # Deploy container
          echo "Deploying container with commit $COMMIT_ID..."
          sudo docker pull kharwararun/app:$COMMIT_ID
          sudo docker stop app || true
          sudo docker rm app || true
          sudo docker run -d --name app -p 5000:5000 kharwararun/app:$COMMIT_ID
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-south-1
