name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # --- Checkout Code ---
    - name: Checkout Code
      uses: actions/checkout@v3

    # --- Build Docker Image ---
    - name: Build Docker Image
      run: |
        docker build -t kharwararun/myapp:latest .

    # --- Log in to Docker Hub ---
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # --- Push Docker Image ---
    - name: Push Docker Image
      run: |
        docker push kharwararun/myapp:latest

    # --- Deploy to EC2 ---
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}     # <-- EC2 Public IP / DNS
        username: ubuntu                  # <-- or ec2-user for Amazon Linux
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Install Docker if missing
          if ! command -v docker &> /dev/null
          then
            echo "Installing Docker..."
            sudo apt update -y || true
            sudo apt install -y docker.io || true
            sudo systemctl enable docker || true
            sudo systemctl start docker || true
          fi

          echo "Deploying container..."
          sudo docker pull kharwararun/myapp:latest
          sudo docker stop myapp || true
          sudo docker rm myapp || true
          sudo docker run -d --name myapp -p 5000:5000 kharwararun/myapp:latest
