name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # --- Checkout Code ---
    - name: Checkout Code
      uses: actions/checkout@v3

    # --- Build Docker Image ---
    - name: Build Docker Image
      run: |
        docker build -t kharwararun/myapp:${GITHUB_SHA} .

    # --- Log in to Docker Hub ---
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # --- Push Docker Image ---
    - name: Push Docker Image
      run: |
        docker push kharwararun/myapp:${GITHUB_SHA}

    # --- Configure AWS Credentials ---
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # --- Deploy to EC2 via SSM ---
    - name: Deploy App on EC2
      run: |
        aws ssm send-command \
          --targets "Key=tag:Name,Values=MyEC2App" \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy latest Docker image" \
          --parameters 'commands=[
            "docker pull kharwararun/myapp:${GITHUB_SHA}",
            "docker stop myapp || true",
            "docker rm myapp || true",
            "docker run -d --name myapp -p 5000:5000 kharwararun/myapp:${GITHUB_SHA}"
          ]'
